# Generated by Django 4.1.1 on 2023-06-12 17:13

import common.constants
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingwindow',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='booking_window',
        ),
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='location',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='bookingwindow',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_windows', to='event.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='event.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.PositiveIntegerField(choices=[(1, 'DANCE'), (2, 'SINGING'), (3, 'MOVIE'), (4, 'SPORTS'), (5, 'MAGIC_SHOW'), (6, 'EXHIBITION'), (999, 'OTHERS')], default=common.constants.EventCategoryType['OTHERS']),
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('type', models.PositiveIntegerField(choices=[(1, 'ECONOMY'), (2, 'PREMIUM'), (99, 'SAME')], default=common.constants.EventPriceType['SAME'])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_plans', to='event.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
